/*
  # Load contacts data

  1. Data Loading
    - Insert all contact records from the provided CSV data
    - Handle duplicate entries with UPSERT functionality
    - Clean and normalize data during insertion

  2. Data Quality
    - Trim whitespace from all text fields
    - Handle empty/null values appropriately
    - Ensure data consistency
*/

-- Insert all contacts data from the provided CSV
INSERT INTO public.contacts (first_name, last_name, provider_npi, organization_code, organization_name, location_code)
VALUES
    ('Abigail', 'Abshire', '1471736637', 'AMMO', 'American Medical Administrators - MO', 'AandM'),
    ('Adrianne', 'Simpson', '1255955907', 'AMMO', 'American Medical Administrators - MO', 'AMMMDRT'),
    ('Alicia', 'Braun', '1295761542', 'AMMO', 'American Medical Administrators - MO', 'AandMSC'),
    ('Amy', 'Hicks', '1023355618', 'AMGA', 'AMGA HC Lab', 'AIVSL'),
    ('Amy', 'Puderbaugh', '1214478409', 'AMMO', 'American Medical Administrators - MO', 'APRCF'),
    ('Andrea', 'Tripoli', '1417731365', 'AMMO', 'American Medical Administrators - MO', 'AMMOALGY'),
    ('Andrew', 'Beach', '1154423535', 'AMMO', 'American Medical Administrators - MO', 'AMMOHCTX'),
    ('Anna', 'Montague', '1336829635', 'AMMO', 'American Medical Administrators - MO', 'AMMOLAB'),
    ('Anne', 'Bates', '1528577700', 'AMMO', 'American Medical Administrators - MO', 'AEL'),
    ('Babatunde', 'Oladiran', '1972619905', 'AMMO', 'American Medical Administrators - MO', 'AELAOB'),
    ('Bonnie', 'Reid', '1962141333', 'AMMO', 'American Medical Administrators - MO', 'AHRE'),
    ('Candace', 'Kirkpatrick', '1437630394', 'AMMO', 'American Medical Administrators - MO', 'AHRN'),
    ('Carolyn', 'Herbert', '1366315778', 'AMMO', 'American Medical Administrators - MO', 'AHRO'),
    ('Christopher', 'Main', '1861409525', 'AMMO', 'American Medical Administrators - MO', 'AHRS'),
    ('Connie', 'Burley', '1014115153', 'AMMO', 'American Medical Administrators - MO', 'AHB'),
    ('Corina', 'Peters', '1861487225', 'AMGA', 'AMGA HC Lab', 'AMGAD'),
    ('Courtney', 'Johnston', '1356178548', 'AMMO', 'American Medical Administrators - MO', 'AHP'),
    ('Crystal', 'Bates', '1417481516', 'AMGA', 'AMGA HC Lab', 'AMGAHCLABFL'),
    ('Crystal', 'Bates', '1417481516', 'AMGA', 'AMGA HC Lab', 'AMGAHC'),
    ('Crystal', 'Dyer', '1053561609', 'AMMO', 'American Medical Administrators - MO', 'AandF'),
    ('Cynthia', 'Chambless', '1053377500', 'AMMO', 'American Medical Administrators - MO', 'BWPNH'),
    ('Cynthia', 'Chambless', '1053377500', 'AMGA', 'AMGA HC Lab', 'ASLA'),
    ('Daniel', 'Harris', '1942332242', 'CSPI', 'Coastal Spine & Pain Institute', 'BMT'),
    ('Danielle', 'Johnson', '1396390653', 'AMGA', 'AMGA HC Lab', 'PLANT'),
    ('Dipenkumar', 'Patel', '1124467499', 'AMGA', 'AMGA HC Lab', '3001070'),
    ('Doc', 'Hogg', '1234567789', 'AMMO', 'American Medical Administrators - MO', 'BevMed'),
    ('Doc', 'Hogg', '1234567789', 'TEST', 'TEST', 'TEST'),
    ('Douglas', 'White', '1568563506', 'AMGA', 'AMGA HC Lab', '3001015'),
    ('Dr. Strange', 'Test Provider', '987654321', 'CSPI', 'Coastal Spine & Pain Institute', 'JSP'),
    ('Dr. Strange', 'Test Provider', '987654321', 'SCNC', 'Southern Crescent Neurological Clinic', 'CL'),
    ('Emily', 'Harris', '1962974741', 'AMMO', 'American Medical Administrators - MO', 'BHCCLLC'),
    ('Emma', 'Wagner', '1831074959', 'AMMO', 'American Medical Administrators - MO', 'BHCC'),
    ('Emmanuel', 'Obi', '1518950540', 'FMC', 'FirstCare Medical Center PC', 'FMC Brownsville'),
    ('Erica', 'Houser', '1497409882', 'AMGA', 'AMGA HC Lab', '3001105'),
    ('Evan', 'Mason', '1659195701', 'AMMO', 'American Medical Administrators - MO', 'CLHCC'),
    ('Fausta', 'Arshad', '1144887091', 'AMMO', 'American Medical Administrators - MO', 'CPHCC'),
    ('Faviola', 'Marin', '1598136350', 'AMMO', 'American Medical Administrators - MO', 'CWHCC'),
    ('Faviola', 'Amoy', '1598363176', 'AMGA', 'AMGA HC Lab', 'GCA13'),
    ('Gabriel', 'Cardenas', '1043521719', 'AMMO', 'American Medical Administrators - MO', 'CPW'),
    ('Haley', 'Clark', '1255012366', 'AMMO', 'American Medical Administrators - MO', 'EMCC'),
    ('James', 'DeLine', '1821091810', 'AMMO', 'American Medical Administrators - MO', 'EWM'),
    ('James', 'Probst', '1530767624', 'AMMO', 'American Medical Administrators - MO', 'FVNH'),
    ('Jayesh', 'Patel', '1548365966', 'AMGA', 'AMGA HC Lab', 'CHLSRHC'),
    ('Jayesh', 'Hughes', '1629200477', 'AMMO', 'American Medical Administrators - MO', 'FMG'),
    ('Jody', 'Pryor', '1629902024', 'AMMO', 'American Medical Administrators - MO', 'FSLC'),
    ('Jonathan', 'Pryor', '1407748571', 'AMMO', 'American Medical Administrators - MO', 'GBNHC'),
    ('Jordan', 'Brotz', '1161473334', 'AMMO', 'American Medical Administrators - MO', 'GBNHP'),
    ('Joseph', 'Carver', '1881444160', 'RBUC', 'RBUC HC Lab', 'RBUC'),
    ('Joseph', 'Essmeyer', '1598841576', 'AMMO', 'American Medical Administrators - MO', 'GCC'),
    ('Joseph', 'Hazan', '1881786560', 'AMMO', 'American Medical Administrators - MO', 'GMC'),
    ('Joshua', 'Marti', '1639760264', 'CSPI', 'Coastal Spine & Pain Institute', 'StratusDX'),
    ('Judith', 'Burroughs', '1961122156', 'AMGA', 'AMGA HC Lab', 'CHSNF31'),
    ('Jyotsnappan', 'Krishnamurthy', '1700868900', 'AMTXSealy', 'AMTX HC Lab - Sealy', 'MCOS'),
    ('Katherine', 'Laytham', '1755959758', 'AMMO', 'American Medical Administrators - MO', 'GMCNRHC'),
    ('Kathy', 'Ervie', '1710230077', 'AMMO', 'American Medical Administrators - MO', 'GMNH'),
    ('Kayla', 'Fuller', '1353790159', 'AMMO', 'American Medical Administrators - MO', 'GRMC'),
    ('Kelechi', 'Emmanuel', '1467105982', 'FMC', 'FirstCare Medical Center PC', 'FMC Jackson'),
    ('Kenneth', 'Lazarus', '1689902888', 'SCNC', 'Southern Crescent Neurological Clinic', 'CL'),
    ('Kerri', 'Lynch', '1013439865', 'AMMO', 'American Medical Administrators - MO', 'GMRH'),
    ('Kristin', 'Wagner', '1205160524', 'AMMO', 'American Medical Administrators - MO', 'GVHCC'),
    ('Kristin', 'Wadley', '1124741715', 'AMMO', 'American Medical Administrators - MO', 'GRLC'),
    ('Laurell', 'Gonder', '1255952897', 'AMMO', 'American Medical Administrators - MO', 'HMDXRHC'),
    ('Lea ann', 'Gonder', '1831632165', 'AMMO', 'American Medical Administrators - MO', 'HMaD'),
    ('Leslie', 'Brown', '1233860039', 'AMMO', 'American Medical Administrators - MO', 'HCC'),
    ('Lindsay', 'Robinson', '1992435694', 'AMGA', 'AMGA HC Lab', 'FPoC'),
    ('Lori', 'Parker', '1801224407', 'AMMO', 'American Medical Administrators - MO', 'HNC'),
    ('Margaret', 'Hart', '1114853050', 'AMMO', 'American Medical Administrators - MO', 'HHCC'),
    ('Markisha', 'Owens', '1922809433', 'AMGA', 'AMGA HC Lab', 'GVS'),
    ('Mary', 'Pierce', '1518563557', 'AMMO', 'American Medical Administrators - MO', 'HACC'),
    ('McKenzie', 'Turner', '1562260750', 'AMMO', 'American Medical Administrators - MO', 'KPAMNR'),
    ('Megan', 'Wood', '1407032996', 'AMMO', 'American Medical Administrators - MO', 'KPAM'),
    ('Melanie', 'Henry', '1552774275', 'AMMO', 'American Medical Administrators - MO', 'LRHCC'),
    ('Melanie', 'Auer', '1952353514', 'AMMO', 'American Medical Administrators - MO', 'LRC'),
    ('Michele', 'Callahan', '1699839430', 'AMMO', 'American Medical Administrators - MO', 'LHSLC'),
    ('Nate', 'Armastrong', '1164958243', 'AMMO', 'American Medical Administrators - MO', 'MaHCC'),
    ('Nicole', 'Guerra', '1124809272', 'AMMO', 'American Medical Administrators - MO', 'MMC'),
    ('Onwura', 'Odiakwo', '1972583446', 'AMGA', 'AMGA HC Lab', 'Harley'),
    ('Ponmary', 'Thomas', 'NE101', 'AMTXSealy', 'AMTX HC Lab - Sealy', 'MCOS'),
    ('Priscilla', 'Priscilla', '1356070371', 'RBUC', 'RBUC HC Lab', 'RBUC'),
    ('Proximity', 'Testing', 'Proximity1', 'AMMO', 'American Medical Administrators - MO', 'MFCandD'),
    ('Proximity', 'Testing', 'Proximity2', 'AMGA', 'AMGA HC Lab', 'JWVRC'),
    ('Proximity', 'Testing', 'Proximity3', 'AMTXStockton', 'AMTX HC Lab - Stockton', 'MallMC'),
    ('Proximity', 'Testing', 'Proximity4', 'CSPI', 'Coastal Spine & Pain Institute', 'BMT'),
    ('Proximity', 'Testing', 'Proximity5', 'SCNC', 'Southern Crescent Neurological Clinic', 'CL'),
    ('Proximity', 'Testing', 'Proximity6', 'TEST', 'TEST', 'TEST'),
    ('Quinn', 'Norwood', '1871343103', 'AMMO', 'American Medical Administrators - MO', 'MFMCarthage'),
    ('Rachelle', 'Chiaramonte', '1014322583', 'AMMO', 'American Medical Administrators - MO', 'MFMColumbus'),
    ('Rasmire', 'Baker', '1326728946', 'AMMO', 'American Medical Administrators - MO', 'MFMGalena'),
    ('Rene', 'Obi', '1012433150', 'FMC', 'FirstCare Medical Center PC', 'FMC Brownsville'),
    ('Richard', 'Amezquita', '1326234816', 'AMMO', 'American Medical Administrators - MO', 'MCMADX'),
    ('Richard', 'Amezquita', '1326234816', 'AMGA', 'AMGA HC Lab', 'OLWW'),
    ('Richard', 'Muckerman', '1434219569', 'AMMO', 'American Medical Administrators - MO', 'McP'),
    ('Richard', 'Wittrock', '1215943105', 'AMMO', 'American Medical Administrators - MO', 'MWBJC'),
    ('Roger', 'Sacy', '1528069629', 'AMMO', 'American Medical Administrators - MO', 'MIGFAC'),
    ('Shawn', 'Patel', '1558503404', 'AMGA', 'AMGA HC Lab', '3001069'),
    ('Shellee', 'Flora', '1871275667', 'AMMO', 'American Medical Administrators - MO', 'MiHCC'),
    ('Sonia', 'Patel', '1395650934', 'AMGA', 'AMGA HC Lab', '3001016'),
    ('Stephanie', 'Clark', '1851755595', 'AMMO', 'American Medical Administrators - MO', 'MMDDRW'),
    ('Subash', 'Mallik', '1285258885', 'AMTXStockton', 'AMTX HC Lab - Stockton', 'MallMC'),
    ('Susan', 'Zhou', '1952974172', 'AMMO', 'American Medical Administrators - MO', 'NRHCC'),
    ('Tabitha', 'Chu', '1230259561', 'AMMO', 'American Medical Administrators - MO', 'NHCHC'),
    ('Test DR', 'Smith', '123456', 'FMC', 'FirstCare Medical Center PC', 'FMC Brownsville'),
    ('Test DR', 'Smith', '123456', 'TEST', 'TEST', 'TEST'),
    ('Tiffany', 'Leeker', '1659562591', 'AMMO', 'American Medical Administrators - MO', 'NHC'),
    ('Tiffany', 'Nelson', '1225565948', 'AMMO', 'American Medical Administrators - MO', 'NVP'),
    ('Timothy', 'McPherson', '1245264696', 'AMMO', 'American Medical Administrators - MO', 'NHCC'),
    ('William', 'Dolan', '1629973721', 'RBUC', 'RBUC HC Lab', 'RBUC')
ON CONFLICT (first_name, last_name, provider_npi, organization_code, location_code) 
DO UPDATE SET
    organization_name = EXCLUDED.organization_name,
    updated_at = now();